FROM ansibleplaybookbundle/apb-base

LABEL "com.redhat.apb.spec"=\
"dmVyc2lvbjogMS4wCm5hbWU6IHNzLWdsdXN0ZXItYXBiCmRlc2NyaXB0aW9uOiBUaGlzIGlzIGEg\
c2FtcGxlIGFwcGxpY2F0aW9uIGdlbmVyYXRlZCBieSBhcGIgaW5pdApiaW5kYWJsZTogRmFsc2UK\
YXN5bmM6IG9wdGlvbmFsCm1ldGFkYXRhOgogIGRpc3BsYXlOYW1lOiBzcy1nbHVzdGVyCiAgZGVw\
ZW5kZW5jaWVzOiBbXQpwbGFuczoKICAtIG5hbWU6IGRlZmF1bHQKICAgIGRlc2NyaXB0aW9uOiBU\
aGlzIGRlZmF1bHQgcGxhbiBkZXBsb3lzIHNzLWdsdXN0ZXItYXBiCiAgICBmcmVlOiBUcnVlCiAg\
ICBtZXRhZGF0YToge30KICAgIHBhcmFtZXRlcnM6IFtd"

COPY playbooks /opt/apb/actions
COPY roles /opt/ansible/roles
RUN chmod -R g=u /opt/{ansible,apb}
USER apb
