---
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: glusterfs
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  zone: us-east-1d
---
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: gluster
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  zone: us-east-1d