---
apiVersion: v1
kind: Service
metadata:
  name: glusterfs
  labels:
    app: glusterfs
    glusterfs: service
spec:
  ports:
  - port: 24007
    name: glusterd
  - port: 24008
    name: management
  clusterIP: None
  selector:
    app: glusterfs
